// Generated by CoffeeScript 1.7.1
(function() {
  var BV, delay, fontsize, wHeight, wWidth, x, y;

  x = 0;

  y = 0;

  BV = 0;

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  window.myvideo = new $.BigVideo();

  BV = window.myvideo;

  BV.init();

  BV.show('video/river.mp4');

  wHeight = $(window).height();

  $(".black").css("height", wHeight + "px");

  wWidth = $(window).width();

  fontsize = wWidth / 560 * 0.7 * 100;

  $("body").css("font-size", fontsize + "%");

  $(window).resize(function() {
    var у;
    clearTimeout(x, y);
    x = setTimeout(function() {
      wHeight = $(window).height();
      $(".black").css("height", wHeight + "px");
      wWidth = $(window).width();
      fontsize = wWidth / 560 * 0.7 * 100;
      return $("body").css("font-size", fontsize + "%");
    }, 180);
    return у = setTimeout(function() {
      return window.myvideo.RESIZE();
    }, 220);
  });

}).call(this);
